name = "Skyler"
uuid = "804faec8-72f5-11ea-307d-47b816e9b733"
keywords = ["topological data analysis", "stratified space learning", "point cloud samples", "modelling embeddings"]
license = "MIT"
desc = "Modelling embeddings of graphs from point cloud samples"
author = "Yossi Bokor <yossi.bokor@anu.edu.au>"
version = "1.0.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimpleGraphs = "55797a34-41de-5266-9ec1-32ac4eb504d3"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"

[compat]
julia = "^1"
CSV = "^0.8.2"
DataFrames = "^0.20.0, ^0.21"
Distances = "^0.8.2"
Distributions = "^0.23.2"
NearestNeighbors = "^0.4.4"
Optim = "^0.20.1, ^0.21"
Plots = "^0.29.1, ^1.0.0"
QuadGK = "^2.3.1"
SimpleGraphs = "0.3.0"
SparseArrays = "1"
ProgressMeter = "1.4.1"
JLD = "^0.10.0"
SpecialFunctions = "^0.10.0, ^1.0.0"
Calculus = "0.5.1"
NNlib = "0.7.0"
FiniteDiff = "2.7.2"

